//! `identity.json` — which repository this store belongs to, and why (`F-MAN-2`, `F-MAN-3`).
//!
//! > `identity.json` records both the resolved key and which tier produced it, so a user can
//! > see why two checkouts did or did not share a store.
//!
//! That sentence is the whole specification, and it is a *user-facing* one: the file exists to
//! be opened and understood, not merely to be parsed. So it is JSON (`N2`, architecture D9),
//! it is pretty-printed, the tier is a word rather than a number, the timestamp is written
//! twice — once as seconds and once as a date a person can read — and it carries a plain
//! sentence saying what the identity means for sharing.
//!
//! # This file is a new one
//!
//! The architecture's file tree names `manifest_io.rs` and `world_io.rs` but no
//! `identity_io.rs`, while still requiring `identity.json` to exist. Reading that as an
//! oversight rather than a decision: persistence lives in `*_io.rs` in this crate, and
//! [`resolve`](crate::resolve) is documented as pure — a normalized URL is a function of a
//! string, and keeping it that way is what makes it exhaustively testable without a
//! filesystem.
//!
//! # Nothing here is trusted
//!
//! A user can edit this file; `N2` invites them to look at it, and looking leads to editing.
//! So [`read`] recomputes the key from the tier and source value it finds and rejects a file
//! whose stored key disagrees, and rejects one sitting in a directory it does not name. The
//! consequence of trusting it would be a store that serves one repository's tree for another.
//!
//! Nothing is lost by refusing: the identity is a function of the repository and is
//! regenerated by opening it (`F-MAN-8`).

use crate::manifest_io::{WriteError, write_atomically};
use crate::paths::RepositoryStore;
use crate::resolve::{RemoteUrl, Resolution, Skipped};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use treepo_model::identity::{CommitId, IdentityTier, RepoIdentity};

/// The version of this file's shape.
///
/// Not `F-MAN-6`'s schema version, which is the manifest's. This one moves when the *fields*
/// here change, and a file at any other version is regenerated rather than read — the same
/// answer, for the same reason, at a hundredth of the cost.
const FORMAT_VERSION: u32 = 1;

/// Why a stored identity could not be read.
#[derive(Debug)]
pub enum IdentityError {
    /// No `identity.json` here. An ordinary first open (`F-MAN-8`).
    Absent,
    /// The filesystem refused.
    Io {
        /// The file being read.
        path: PathBuf,
        /// What it said.
        source: std::io::Error,
    },
    /// Not JSON, not this format's version, or a field this build does not understand.
    Malformed {
        /// The file that was read.
        path: PathBuf,
        /// What was wrong.
        detail: String,
    },
    /// The file parsed and then contradicted itself.
    ///
    /// A key that is not the hash of the tier and source value beside it, or an identity in a
    /// directory named after a different one. Both mean the file was edited or moved, and both
    /// are worth distinguishing from a parse failure — this one says the *store* is wrong
    /// rather than the file.
    Inconsistent {
        /// What did not add up.
        detail: String,
    },
}

impl std::fmt::Display for IdentityError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Absent => write!(f, "no identity recorded yet"),
            Self::Io { path, source } => write!(f, "reading {}: {source}", path.display()),
            Self::Malformed { path, detail } => {
                write!(f, "{} is not readable: {detail}", path.display())
            }
            Self::Inconsistent { detail } => {
                write!(f, "the stored identity does not add up: {detail}")
            }
        }
    }
}

impl std::error::Error for IdentityError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            _ => None,
        }
    }
}

impl IdentityError {
    /// Whether the right response is to resolve the identity again.
    ///
    /// True for everything but an I/O failure — resolving costs a config read, so there is
    /// never a reason to limp along with a file that does not make sense.
    #[must_use]
    pub const fn is_regenerable(&self) -> bool {
        !matches!(self, Self::Io { .. })
    }
}

/// Writes `identity.json` into `store`, atomically (`F-MAN-2`, `F-MAN-7`).
///
/// # Errors
///
/// [`WriteError`] if the directory cannot be created or the file cannot be written.
pub fn write(store: &RepositoryStore, resolution: &Resolution) -> Result<(), WriteError> {
    let mut text =
        serde_json::to_string_pretty(&StoredIdentity::from(resolution)).unwrap_or_default();
    text.push('\n');
    write_atomically(&store.identity_file(), text.as_bytes())
}

/// Reads the identity `store` records, checking it against itself and against its directory.
///
/// # Errors
///
/// [`IdentityError::Absent`] when there is none — the ordinary first open. See
/// [`IdentityError::is_regenerable`] for the rest.
pub fn read(store: &RepositoryStore) -> Result<Resolution, IdentityError> {
    let path = store.identity_file();
    let text = match std::fs::read_to_string(&path) {
        Ok(text) => text,
        Err(source) if source.kind() == std::io::ErrorKind::NotFound => {
            return Err(IdentityError::Absent);
        }
        Err(source) => return Err(IdentityError::Io { path, source }),
    };

    let stored: StoredIdentity =
        serde_json::from_str(&text).map_err(|error| IdentityError::Malformed {
            path: path.clone(),
            detail: error.to_string(),
        })?;
    if stored.version != FORMAT_VERSION {
        return Err(IdentityError::Malformed {
            path,
            detail: format!(
                "written in format {} and this build reads {FORMAT_VERSION}",
                stored.version
            ),
        });
    }

    let resolution = stored.into_resolution(&path)?;
    let directory = store
        .dir()
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or_default();
    if directory != resolution.identity.directory_name() {
        return Err(IdentityError::Inconsistent {
            detail: format!(
                "it names a repository whose store is {}, but it is sitting in {directory}",
                resolution.identity.directory_name()
            ),
        });
    }
    Ok(resolution)
}

/// Wall-clock seconds, for [`RepoIdentity::resolved_at`].
///
/// **The only clock reading in the product's own crates.** `N3` bans `SystemTime::now`
/// workspace-wide because a generated value that depends on when it was generated destroys
/// `AC-DET-1`; this one is store housekeeping — how `F-MAN-9`'s browser shows a last-opened
/// time — and it is confined here so that "does treepo read the clock, and where" has one
/// answer that can be checked.
///
/// It is not hashed into the identity key, and `treepo-model` states the same rule from the
/// other side: nothing in `treepo-gen` or `treepo-grow` may read `resolved_at`.
///
/// Zero before 1970, which no filesystem will produce and which is a better answer than a
/// panic in a housekeeping field.
#[must_use]
#[expect(
    clippy::disallowed_methods,
    clippy::disallowed_types,
    reason = "N3's one sanctioned clock read, narrowed to this function; see the doc comment"
)]
pub fn now() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::SystemTime::UNIX_EPOCH)
        .map_or(0, |elapsed| elapsed.as_secs())
}

// ---------------------------------------------------------------------------------------
// The stored shape.
// ---------------------------------------------------------------------------------------

/// `identity.json`, as written.
///
/// Field order is the order a person reads them in: what this is, then why, then when.
#[derive(Debug, Serialize, Deserialize)]
struct StoredIdentity {
    version: u32,
    /// The plain sentence answering "why did these two checkouts share a store?".
    ///
    /// Written for people and never read back — [`Resolution`] carries the structured form.
    #[serde(default, skip_deserializing)]
    explanation: String,
    key: String,
    tier: String,
    source_value: String,
    resolved_at: u64,
    /// The same instant as `resolved_at`, spelled for a human. Written, never read.
    #[serde(default, skip_deserializing)]
    resolved_at_utc: String,
    derivation: StoredDerivation,
}

#[derive(Debug, Default, Serialize, Deserialize)]
struct StoredDerivation {
    /// The remote tier 1 used, by name.
    chosen_remote: Option<String>,
    /// Every remote considered, in name order. Normalized only — a raw URL can carry a
    /// credential, and `resolve` strips them before anything reaches this file.
    remotes: Vec<StoredRemote>,
    /// The root commit, when tier 2 resolved one.
    root_commit: Option<String>,
    /// Why each tier above the winning one did not apply.
    skipped: Vec<StoredSkip>,
}

#[derive(Debug, Serialize, Deserialize)]
struct StoredRemote {
    name: String,
    normalized_url: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
struct StoredSkip {
    /// A stable machine name, so a later release can act on this without parsing prose.
    code: String,
    /// The sentence a user reads.
    #[serde(default, skip_deserializing)]
    reason: String,
}

impl From<&Resolution> for StoredIdentity {
    fn from(resolution: &Resolution) -> Self {
        let Resolution {
            identity,
            remotes,
            chosen,
            root_commit,
            skipped,
        } = resolution;
        Self {
            version: FORMAT_VERSION,
            explanation: explain(identity),
            key: identity.directory_name(),
            tier: tier_name(identity.tier).to_string(),
            source_value: identity.source_value.clone(),
            resolved_at: identity.resolved_at,
            resolved_at_utc: utc_timestamp(identity.resolved_at),
            derivation: StoredDerivation {
                chosen_remote: chosen.clone(),
                remotes: remotes
                    .iter()
                    .map(|remote| {
                        let RemoteUrl { name, normalized } = remote;
                        StoredRemote {
                            name: name.clone(),
                            normalized_url: normalized.clone(),
                        }
                    })
                    .collect(),
                root_commit: root_commit.map(|id| id.to_string()),
                skipped: skipped
                    .iter()
                    .map(|skip| StoredSkip {
                        code: skip_code(*skip).to_string(),
                        reason: skip.reason().to_string(),
                    })
                    .collect(),
            },
        }
    }
}

impl StoredIdentity {
    fn into_resolution(self, path: &std::path::Path) -> Result<Resolution, IdentityError> {
        let malformed = |detail: String| IdentityError::Malformed {
            path: path.to_path_buf(),
            detail,
        };

        let tier = tier_from_name(&self.tier)
            .ok_or_else(|| malformed(format!("unknown identity tier `{}`", self.tier)))?;
        // Recomputed rather than trusted: the key is *defined* as the hash of the two fields
        // above it, and a file claiming otherwise has been edited.
        let identity = RepoIdentity::new(tier, self.source_value, self.resolved_at);
        if identity.directory_name() != self.key {
            return Err(IdentityError::Inconsistent {
                detail: format!(
                    "its key is not the hash of its own tier and source value — recorded {}, \
                     computed {}",
                    self.key,
                    identity.directory_name()
                ),
            });
        }

        let mut skipped = Vec::with_capacity(self.derivation.skipped.len());
        for skip in self.derivation.skipped {
            skipped.push(
                skip_from_code(&skip.code)
                    .ok_or_else(|| malformed(format!("unknown skip code `{}`", skip.code)))?,
            );
        }

        Ok(Resolution {
            identity,
            remotes: self
                .derivation
                .remotes
                .into_iter()
                .map(|remote| RemoteUrl {
                    name: remote.name,
                    normalized: remote.normalized_url,
                })
                .collect(),
            chosen: self.derivation.chosen_remote,
            root_commit: self
                .derivation
                .root_commit
                .map(|hex| commit_from_hex(&hex))
                .transpose()
                .map_err(malformed)?,
            skipped,
        })
    }
}

/// The sentence `F-MAN-3` asks this file to make answerable.
fn explain(identity: &RepoIdentity) -> String {
    match identity.tier {
        IdentityTier::Remote => format!(
            "Identified by its remote URL, so every clone of {} shares this store — including \
             one at a different path, and one on a different branch.",
            identity.source_value
        ),
        IdentityTier::RootCommit => {
            "Identified by its first commit, because it has no remote configured. Moving or \
             renaming the folder keeps this store; a fork or a copy with the same history \
             shares it."
                .to_string()
        }
        IdentityTier::PathHash => format!(
            "Identified by its location, {}, because there was no remote and no commit to \
             identify it by. Moving the folder will start a new store.",
            identity.source_value
        ),
    }
}

// Names rather than numbers, written out in both directions. A `Serialize` derive on
// `IdentityTier` would put a variant name in the file and tie the format to a Rust
// identifier; writing them here means renaming a variant is a Rust refactor and renaming a
// stored value is a format decision.

const fn tier_name(tier: IdentityTier) -> &'static str {
    match tier {
        IdentityTier::Remote => "remote-url",
        IdentityTier::RootCommit => "root-commit",
        IdentityTier::PathHash => "path-hash",
    }
}

fn tier_from_name(name: &str) -> Option<IdentityTier> {
    match name {
        "remote-url" => Some(IdentityTier::Remote),
        "root-commit" => Some(IdentityTier::RootCommit),
        "path-hash" => Some(IdentityTier::PathHash),
        _ => None,
    }
}

const fn skip_code(skipped: Skipped) -> &'static str {
    match skipped {
        Skipped::NoRepository => "no-repository",
        Skipped::NoRemotes => "no-remotes",
        Skipped::NoRemoteUrl => "no-remote-url",
        Skipped::NoCommits => "no-commits",
        Skipped::TruncatedHistory => "truncated-history",
        Skipped::NoRootCommit => "no-root-commit",
    }
}

fn skip_from_code(code: &str) -> Option<Skipped> {
    match code {
        "no-repository" => Some(Skipped::NoRepository),
        "no-remotes" => Some(Skipped::NoRemotes),
        "no-remote-url" => Some(Skipped::NoRemoteUrl),
        "no-commits" => Some(Skipped::NoCommits),
        "truncated-history" => Some(Skipped::TruncatedHistory),
        "no-root-commit" => Some(Skipped::NoRootCommit),
        _ => None,
    }
}

fn commit_from_hex(hex: &str) -> Result<CommitId, String> {
    let bytes: Result<Vec<u8>, String> = hex
        .as_bytes()
        .chunks(2)
        .map(|pair| {
            std::str::from_utf8(pair)
                .ok()
                .and_then(|pair| u8::from_str_radix(pair, 16).ok())
                .ok_or_else(|| format!("`{hex}` is not a hexadecimal object id"))
        })
        .collect();
    let bytes = bytes?;
    match bytes.len() {
        20 => Ok(CommitId::sha1(bytes.try_into().unwrap_or([0; 20]))),
        32 => Ok(CommitId::sha256(bytes.try_into().unwrap_or([0; 32]))),
        other => Err(format!("object id is {other} bytes, not 20 or 32")),
    }
}

/// `YYYY-MM-DDThh:mm:ssZ` for a Unix timestamp, by integer arithmetic alone.
///
/// Howard Hinnant's `civil_from_days`, which is exact for every date this will ever see. A
/// date library would be a dependency for one cosmetic field, and a float would be `N3`'s
/// problem in a file that is otherwise beyond its reach.
fn utc_timestamp(seconds: u64) -> String {
    let days = (seconds / 86_400) as i64;
    let time = seconds % 86_400;

    // Shift the epoch to 0000-03-01 so leap days land at the end of the year.
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let day_of_era = z.rem_euclid(146_097);
    let year_of_era =
        (day_of_era - day_of_era / 1_460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let shifted_month = (5 * day_of_year + 2) / 153;

    let day = day_of_year - (153 * shifted_month + 2) / 5 + 1;
    let month = if shifted_month < 10 {
        shifted_month + 3
    } else {
        shifted_month - 9
    };
    let year = year_of_era + era * 400 + i64::from(month <= 2);

    format!(
        "{year:04}-{month:02}-{day:02}T{:02}:{:02}:{:02}Z",
        time / 3_600,
        (time % 3_600) / 60,
        time % 60
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::StoreRoot;

    fn store_with(name: &str, tier: IdentityTier) -> (RepositoryStore, Resolution) {
        let dir = std::env::temp_dir().join("treepo-identity-io").join(name);
        if dir.exists() {
            std::fs::remove_dir_all(&dir).expect("clearing scratch");
        }
        let resolution = resolution(tier);
        let store = StoreRoot::at(dir).repository(&resolution.identity);
        (store, resolution)
    }

    fn resolution(tier: IdentityTier) -> Resolution {
        let source = match tier {
            IdentityTier::Remote => "github.com/example/widget",
            IdentityTier::RootCommit => "a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7",
            IdentityTier::PathHash => "/home/u/src/widget",
        };
        Resolution {
            identity: RepoIdentity::new(tier, source.to_string(), 1_785_000_000),
            remotes: vec![
                RemoteUrl {
                    name: "backup".to_string(),
                    normalized: None,
                },
                RemoteUrl {
                    name: "origin".to_string(),
                    normalized: Some("github.com/example/widget".to_string()),
                },
            ],
            chosen: (tier == IdentityTier::Remote).then(|| "origin".to_string()),
            root_commit: (tier == IdentityTier::RootCommit).then(|| CommitId::sha1([0xa7; 20])),
            skipped: match tier {
                IdentityTier::Remote => Vec::new(),
                IdentityTier::RootCommit => vec![Skipped::NoRemotes],
                IdentityTier::PathHash => vec![Skipped::NoRemotes, Skipped::NoCommits],
            },
        }
    }

    /// Every tier must survive the round trip, including its derivation.
    #[test]
    fn each_tier_round_trips_through_the_file() {
        for tier in [
            IdentityTier::Remote,
            IdentityTier::RootCommit,
            IdentityTier::PathHash,
        ] {
            let (store, original) = store_with(&format!("round-trip-{}", tier_name(tier)), tier);
            write(&store, &original).expect("the write");
            let read_back = read(&store).expect("the read");
            assert_eq!(original, read_back, "{tier:?}");
        }
    }

    /// `N2` — the file has to be legible, not merely parseable.
    #[test]
    fn the_file_answers_why_two_checkouts_share_a_store() {
        let (store, resolution) = store_with("legible", IdentityTier::Remote);
        write(&store, &resolution).expect("the write");
        let text = std::fs::read_to_string(store.identity_file()).expect("the file");

        for expected in [
            "\"tier\": \"remote-url\"",
            "\"source_value\": \"github.com/example/widget\"",
            "\"chosen_remote\": \"origin\"",
            "\"resolved_at_utc\": \"2026-07-25T17:20:00Z\"",
            "every clone of github.com/example/widget shares this store",
        ] {
            assert!(text.contains(expected), "missing {expected}:\n{text}");
        }
        assert!(text.ends_with('\n'), "editors expect a trailing newline");

        // A tier that did not apply says so in words as well as in a code.
        let (skipping, resolution) = store_with("legible-skips", IdentityTier::PathHash);
        write(&skipping, &resolution).expect("the write");
        let text = std::fs::read_to_string(skipping.identity_file()).expect("the file");
        assert!(text.contains("\"code\": \"no-commits\""));
        assert!(text.contains("This repository has no commits yet"));
    }

    /// A hand-edited key must be refused, or the store serves one repository's tree for
    /// another.
    #[test]
    fn a_key_that_is_not_the_hash_of_its_own_fields_is_refused() {
        let (store, resolution) = store_with("edited-key", IdentityTier::Remote);
        write(&store, &resolution).expect("the write");

        let path = store.identity_file();
        let text = std::fs::read_to_string(&path).expect("the file");
        let tampered = text.replace("github.com/example/widget", "github.com/attacker/widget");
        std::fs::write(&path, tampered).expect("rewriting");

        let error = read(&store).expect_err("the key no longer matches");
        assert!(matches!(error, IdentityError::Inconsistent { .. }));
        assert!(error.is_regenerable());
        assert!(error.to_string().contains("not the hash of its own"));
    }

    /// A store directory copied under another name is not that other repository's store.
    ///
    /// The realistic route to this is a user copying an app-data directory between machines
    /// and renaming one by hand. Trusting the file over the directory would hand them one
    /// repository's tree under another repository's name.
    #[test]
    fn an_identity_in_the_wrong_directory_is_refused() {
        let dir = std::env::temp_dir()
            .join("treepo-identity-io")
            .join("wrong-directory");
        if dir.exists() {
            std::fs::remove_dir_all(&dir).expect("clearing scratch");
        }
        let root = StoreRoot::at(dir);

        let real = resolution(IdentityTier::Remote);
        let real_store = root.repository(&real.identity);
        write(&real_store, &real).expect("the write");

        // A second, genuine store for a different repository — then the first one's file
        // copied into it, which is exactly what a hand-copied directory looks like.
        let other = RepoIdentity::new(
            IdentityTier::Remote,
            "github.com/someone/other".to_string(),
            0,
        );
        let impostor = root.repository(&other);
        assert_ne!(impostor.dir(), real_store.dir());
        std::fs::create_dir_all(impostor.dir()).expect("the other directory");
        std::fs::copy(real_store.identity_file(), impostor.identity_file()).expect("the copy");

        let error = read(&impostor).expect_err("it names a different repository");
        assert!(matches!(error, IdentityError::Inconsistent { .. }));
        assert!(error.is_regenerable());
        assert!(error.to_string().contains("sitting in"));
        // And the original still reads, so the check is about placement, not the file.
        assert_eq!(read(&real_store).expect("still fine"), real);
    }

    #[test]
    fn a_missing_or_unreadable_file_asks_for_regeneration() {
        let (store, resolution) = store_with("missing", IdentityTier::Remote);
        let absent = read(&store).expect_err("nothing written yet");
        assert!(matches!(absent, IdentityError::Absent));
        assert!(absent.is_regenerable());

        write(&store, &resolution).expect("the write");
        std::fs::write(store.identity_file(), "{ not json").expect("corrupting");
        let malformed = read(&store).expect_err("not JSON");
        assert!(matches!(malformed, IdentityError::Malformed { .. }));
        assert!(malformed.is_regenerable());

        let text = serde_json::to_string(&serde_json::json!({
            "version": FORMAT_VERSION + 1,
            "key": "0",
            "tier": "remote-url",
            "source_value": "x",
            "resolved_at": 0,
            "derivation": { "chosen_remote": null, "remotes": [], "root_commit": null, "skipped": [] }
        }))
        .expect("json");
        std::fs::write(store.identity_file(), text).expect("writing a future format");
        let future = read(&store).expect_err("a newer format");
        assert!(matches!(future, IdentityError::Malformed { .. }));
        assert!(future.to_string().contains("this build reads"));
    }

    /// Known instants, so the date arithmetic is checked against something rather than
    /// against itself.
    #[test]
    fn utc_timestamps_are_correct_at_the_awkward_dates() {
        for (seconds, expected) in [
            (0u64, "1970-01-01T00:00:00Z"),
            (951_782_400, "2000-02-29T00:00:00Z"), // a leap day in a leap century
            (1_078_012_800, "2004-02-29T00:00:00Z"),
            (1_709_164_800, "2024-02-29T00:00:00Z"),
            (1_785_000_000, "2026-07-25T17:20:00Z"),
            (2_147_483_647, "2038-01-19T03:14:07Z"), // where a 32-bit clock would stop
            (1_609_459_199, "2020-12-31T23:59:59Z"),
        ] {
            assert_eq!(utc_timestamp(seconds), expected, "at {seconds}");
        }
    }

    /// The one clock read has to actually work, and has to be seconds rather than millis.
    #[test]
    fn the_clock_reads_plausible_seconds() {
        let seconds = now();
        assert!(seconds > 1_700_000_000, "after 2023");
        assert!(seconds < 4_000_000_000, "before 2096");
        assert!(utc_timestamp(seconds).starts_with("20"));
    }

    /// Enum codes are the format; a duplicate or a broken round trip changes what a file
    /// means.
    #[test]
    fn tier_and_skip_codes_round_trip() {
        let mut names = Vec::new();
        for tier in [
            IdentityTier::Remote,
            IdentityTier::RootCommit,
            IdentityTier::PathHash,
        ] {
            let name = tier_name(tier);
            assert_eq!(tier_from_name(name), Some(tier));
            assert!(!names.contains(&name), "duplicate tier name {name}");
            names.push(name);
        }
        assert_eq!(tier_from_name("tier-1"), None);

        let mut codes = Vec::new();
        for skipped in [
            Skipped::NoRepository,
            Skipped::NoRemotes,
            Skipped::NoRemoteUrl,
            Skipped::NoCommits,
            Skipped::TruncatedHistory,
            Skipped::NoRootCommit,
        ] {
            let code = skip_code(skipped);
            assert_eq!(skip_from_code(code), Some(skipped));
            assert!(!codes.contains(&code), "duplicate skip code {code}");
            codes.push(code);
        }
        assert_eq!(skip_from_code("no-idea"), None);
    }

    #[test]
    fn object_ids_parse_at_both_widths_and_fail_otherwise() {
        assert_eq!(
            commit_from_hex(&"a7".repeat(20)),
            Ok(CommitId::sha1([0xa7; 20]))
        );
        assert_eq!(
            commit_from_hex(&"5c".repeat(32)),
            Ok(CommitId::sha256([0x5c; 32]))
        );
        assert!(commit_from_hex("abc").is_err());
        assert!(commit_from_hex(&"zz".repeat(20)).is_err());
    }
}
