//! `F-MAT-6` — what is wrong with a surface, drawn over the top of everything else.
//!
//! > Quality/debt signals introduce subtle stress materials (cracks, sparse density) coexisting
//! > with the primary material.
//!
//! `design/feature-system.md` §8.5: "high TODO / debt signals can introduce subtle stress
//! materials (cracks, sparse density, restless micro-particles) that **coexist** with the primary
//! material". [`material`](crate::material) decides what a limb is made of and
//! [`enrich`](mod@crate::enrich) decides what is built on it; this decides nothing about either. It
//! adds a reading, and [`Stress`] is a field beside the others rather than a competing value of
//! any of them — which is what "coexist" means, expressed as a type instead of as care.
//!
//! # Three appearances, one signal each
//!
//! | Kind | Signal | Primitive |
//! |---|---|---|
//! | [`Cracked`](StressKind::Cracked) | `todo_density`, linear against a marker scale | [`DerivedSignals`](treepo_model::DerivedSignals) (`F-EXT-6`) |
//! | [`Sparse`](StressKind::Sparse) | `large_file_debt` | [`DerivedSignals`](treepo_model::DerivedSignals) (`F-EXT-6`) |
//! | [`Restless`](StressKind::Restless) | `1 - stability` | [`TemporalPrimitives`](treepo_model::TemporalPrimitives) (`F-EXT-2` × `F-EXT-4`) |
//!
//! One signal per kind, and which one is code rather than a row in `materials.ron` — the same
//! decision [`enrich`](mod@crate::enrich)'s `signal_of` records, and for the same reason: a table
//! permitted to re-point a signal is a table that could make the picture say something else.
//! What the table tunes is how much of a signal it takes and how strongly the result shows.
//!
//! The readings are each a plain claim about the content. A crack is the *author's own* marker —
//! a `TODO` is a developer writing "this is unfinished", and treepo is repeating it rather than
//! judging it. Sparseness is a measurement of shape: `large_file_debt` is the share of a subtree's
//! bytes sitting in files over the large-file threshold, so a limb whose mass is two enormous
//! blobs has few, coarse grains where one of a thousand ordinary files has many fine ones.
//! Restlessness is a measurement of motion: `stability` is recent churn against the path's own
//! line count, so inverting it gives "how much of this is being rewritten right now", which is
//! §8.5's "restless" and §8.8's "slight visual unease" reading the same number.
//!
//! # Three signals deliberately not read
//!
//! `F-EXT-6` and §3.5 offer more debt indicators than are used here, and the omissions are
//! decisions rather than an unfinished list.
//!
//! **`generated_debt` — already spent.** It is generated bytes over total bytes, which is
//! precisely the ratio `F-MAT-1` uses to make a limb
//! [`Machined`](treepo_model::MaterialFamily::Machined). Reading it again as stress would draw one
//! fact twice, and a limb of generated output would be both machined *and* cracked for being
//! machined.
//!
//! **`test_to_source` and `comment_density` — they would require an opinion.** Both are low where
//! the debt is, so a stress built on either has to decide how many tests a project ought to have
//! or how much commenting is enough. That is treepo holding a view about how software should be
//! written, and [`Stone`](treepo_model::MaterialFamily::Stone) already settled the principle in
//! the other direction: `N4`'s refusal to judge people extends to not editorializing about their
//! files. The three signals above need no such view — a marker scale says how many of the
//! author's own markers fill the range, which is a normalization, not a prescription.
//!
//! **`doc_staleness_days` — it would land on the wrong material.** It compares the newest
//! documentation commit in a subtree against the newest code commit, so it is a relation *between*
//! two categories rather than a property of either. Drawn as stress on a whole limb it would crack
//! the source code because the README is old, attributing one material's debt to another. It is
//! also signed and unbounded, and would need a scale nothing else here wants.
//!
//! # The floor is on the signal and the ceiling is on the result
//!
//! [`Floors`] cut noise at the bottom: a single marker in a large subtree is not a crack. The
//! [`ceiling`](Rules::ceiling) holds the top down, and it is `F-MAT-6`'s own word "subtle"
//! transcribed into a row rather than left to taste — [`validate`](Rules::validate) refuses a
//! ceiling above half, because past that the stress material is what the limb is made of and the
//! primary material has become the accent, which is the requirement inverted.
//!
//! The two act on different values on purpose. Were the floor applied to the scaled result,
//! raising the ceiling would push content past the floor and start building stress that was not
//! there before — one knob moving the other, which is the failure `blend_floor`'s own bound is
//! written to avoid.

use crate::material::{DebtSignals, Table};
use crate::params::per_mille;
use core::fmt;
use serde::Deserialize;
use treepo_det::Fx;
use treepo_model::material::{Stress, StressKind};

/// `F-MAT-6`'s rules, as data — a section of `assets/params/materials.ron`.
///
/// In that file rather than one of its own for the reason
/// [`Rules`](crate::enrich::Rules) is: stress is a treatment *of* material, and it reads the
/// marker scale that sits with the other three absolute scales in
/// [`Normalize`](crate::normalize::Normalize). Two files would be two places to look for the
/// numbers that make a tree look the way it does.
///
/// Every field is an integer in a stated unit, the convention the rest of the file uses because
/// `N3` keeps floats out of anything reaching generated output.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Rules {
    /// The most intensity any stress may reach, per mille.
    ///
    /// `F-MAT-6`'s word is "subtle", and this is that word as a number. A signal at its full
    /// scale produces this much stress and no more, so the primary material is always the larger
    /// part of what a viewer sees.
    ///
    /// Refused above 500 — see the module header.
    pub ceiling: i32,
    /// How much of each signal it takes before anything is drawn.
    pub present_at: Floors,
}

/// The per-kind noise floors, in per mille of each kind's own signal.
///
/// Named fields rather than an array indexed by [`StressKind::position`], because this file is
/// read and edited by a person — and a `match` in [`of`](Self::of) means a kind added without a
/// floor does not compile. Same shape as [`Kinds`](crate::enrich::Kinds).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Floors {
    /// Marker density below which a surface is not cracked.
    pub cracked: i32,
    /// Large-file share below which a surface is not sparse.
    pub sparse: i32,
    /// Instability below which a surface is not restless.
    pub restless: i32,
}

impl Floors {
    /// One kind's floor.
    #[must_use]
    pub const fn of(&self, kind: StressKind) -> i32 {
        match kind {
            StressKind::Cracked => self.cracked,
            StressKind::Sparse => self.sparse,
            StressKind::Restless => self.restless,
        }
    }
}

impl Table {
    /// What is wrong with one node's surface — `F-MAT-6` over gathered signals.
    ///
    /// `None` where none of the three signals was measured, which [`Stress::new`] decides so that
    /// this function cannot claim a clean surface it never looked at. An unmeasured signal stays
    /// unmeasured through the floor and the ceiling alike: neither a floor nor a scale can turn
    /// "nobody read this file" into "there is nothing wrong with it".
    #[must_use]
    pub fn stress_of(&self, debt: &DebtSignals) -> Option<Stress> {
        let ceiling = per_mille(self.stress.ceiling);
        Stress::new(StressKind::ALL.map(|kind| {
            let signal = self.stress_signal_of(kind, debt)?;
            Some(if signal < per_mille(self.stress.present_at.of(kind)) {
                Fx::ZERO
            } else {
                signal.mul(ceiling)
            })
        }))
    }

    /// How strongly one kind's signal reads, in `0..=1`, or `None` if it was not measured.
    ///
    /// See the module header for where each comes from and for the three that do not appear.
    fn stress_signal_of(&self, kind: StressKind, debt: &DebtSignals) -> Option<Fx> {
        match kind {
            StressKind::Cracked => Some(self.normalize.debt(debt.markers_per_thousand?)),
            // Already a share of the subtree's bytes, so there is no scale to apply — clamped
            // only because a normalized signal that could exceed one would put the ceiling above
            // itself.
            StressKind::Sparse => Some(debt.large_file_share?.clamp(Fx::ZERO, Fx::ONE)),
            // Inverted: `stability` is 1 for untouched and 0 for a path churning at or above its
            // own line count, and what this kind draws is the churning end.
            StressKind::Restless => Some(Fx::ONE.sub(debt.stability?.clamp(Fx::ZERO, Fx::ONE))),
        }
    }
}

impl Rules {
    /// Checks the section against the rules `F-MAT-6` and `P6` state.
    ///
    /// # Errors
    ///
    /// The first violated rule, naming the row and the requirement it came from.
    pub fn validate(&self) -> Result<(), StressError> {
        // Above half, the stress material is what the limb is made of and the primary material is
        // the accent — `F-MAT-6` says the two coexist, and that is the requirement inverted. Zero
        // would place no stress at all while the floors below looked configured, which is the
        // failure `clamp_beyond == 0` is refused for.
        if !(1..=500).contains(&self.ceiling) {
            return Err(StressError {
                row: "ceiling",
                kind: None,
                detail: "the stress ceiling is an intensity in 1..=500 per mille — F-MAT-6 says \
                         stress coexists with the primary material, and past half it has \
                         replaced it",
            });
        }

        for kind in StressKind::ALL {
            let floor = self.present_at.of(kind);
            // Zero would build a crack out of a rounding artefact; a full scale would mean only
            // a surface made of nothing but debt could ever show any.
            if !(1..=1000).contains(&floor) {
                return Err(StressError {
                    row: "present_at",
                    kind: Some(kind),
                    detail: "a presence floor is a share of the kind's signal in 1..=1000 \
                             per mille",
                });
            }
        }

        Ok(())
    }
}

/// Why a stress section was refused.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StressError {
    /// The row that failed.
    pub row: &'static str,
    /// The kind whose row it was, for the per-kind rows.
    pub kind: Option<StressKind>,
    /// The rule it broke, and where the rule comes from.
    pub detail: &'static str,
}

impl fmt::Display for StressError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.kind {
            Some(kind) => write!(
                f,
                "materials.ron: `stress.{}.{}` — {}",
                self.row,
                kind.name(),
                self.detail
            ),
            None => write!(f, "materials.ron: `stress.{}` — {}", self.row, self.detail),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn table() -> Table {
        Table::built_in()
    }

    /// Every signal measured and every one of them at its worst.
    fn ruined() -> DebtSignals {
        DebtSignals {
            markers_per_thousand: Some(Fx::from_int(1000)),
            large_file_share: Some(Fx::ONE),
            stability: Some(Fx::ZERO),
        }
    }

    /// Every signal measured and every one of them clean.
    fn sound() -> DebtSignals {
        DebtSignals {
            markers_per_thousand: Some(Fx::ZERO),
            large_file_share: Some(Fx::ZERO),
            stability: Some(Fx::ONE),
        }
    }

    #[test]
    fn the_shipped_section_validates() {
        assert_eq!(table().stress.validate(), Ok(()));
    }

    /// `F-MAT-6`'s word is "subtle", and the ceiling is that word. Even a surface that is
    /// nothing but debt on every axis stays a minority of what a viewer sees.
    #[test]
    fn nothing_reaches_more_than_the_ceiling() {
        let table = table();
        let ceiling = per_mille(table.stress.ceiling);
        let stress = table.stress_of(&ruined()).expect("everything was measured");

        assert_eq!(stress.count(), 3, "all three kinds fire on this");
        for (kind, intensity) in stress.present() {
            assert_eq!(intensity, ceiling, "{kind:?} exceeded the ceiling");
        }
        assert!(ceiling <= Fx::HALF, "and the ceiling is a minority share");
    }

    /// A healthy surface reads as measured and clean, which is a finding — not the absence of
    /// one, and not `None`.
    #[test]
    fn a_sound_surface_is_measured_and_clear() {
        let stress = table()
            .stress_of(&sound())
            .expect("everything was measured");
        assert!(stress.is_clear());
        for kind in StressKind::ALL {
            assert_eq!(stress.intensity_of(kind), Some(Fx::ZERO), "{kind:?}");
        }
    }

    /// The distinction the whole `Option` layering exists for, through the pass rather than on
    /// the type: a file nothing read has nothing said about it.
    #[test]
    fn an_unmeasured_signal_stays_unmeasured() {
        let table = table();
        assert_eq!(
            table.stress_of(&DebtSignals::default()),
            None,
            "nothing measured is not a clean surface"
        );

        // A binary blob: no text was scanned and it has no line count to divide churn by, so
        // only its shape is known.
        let blob = DebtSignals {
            markers_per_thousand: None,
            large_file_share: Some(Fx::ONE),
            stability: None,
        };
        let stress = table.stress_of(&blob).expect("its shape was measured");
        assert_eq!(stress.intensity_of(StressKind::Cracked), None);
        assert_eq!(stress.intensity_of(StressKind::Restless), None);
        assert_eq!(
            stress.intensity_of(StressKind::Sparse),
            Some(per_mille(table.stress.ceiling))
        );
        assert_eq!(stress.count(), 1);
    }

    /// `P6` at the small end: a trace of debt is not a crack. And the floor is a floor on the
    /// *signal*, so it is not moved by the ceiling.
    #[test]
    fn a_trace_of_debt_draws_nothing() {
        let table = table();
        let floors = &table.stress.present_at;

        // Just under each kind's floor, one kind at a time.
        let barely = |kind: StressKind| -> DebtSignals {
            let under = per_mille(floors.of(kind)).sub(Fx::from_ratio(1, 1000));
            match kind {
                StressKind::Cracked => DebtSignals {
                    markers_per_thousand: Some(
                        under.mul(Fx::from_int(table.normalize.todo_full_scale_per_thousand)),
                    ),
                    ..DebtSignals::default()
                },
                StressKind::Sparse => DebtSignals {
                    large_file_share: Some(under),
                    ..DebtSignals::default()
                },
                StressKind::Restless => DebtSignals {
                    stability: Some(Fx::ONE.sub(under)),
                    ..DebtSignals::default()
                },
            }
        };

        for kind in StressKind::ALL {
            let stress = table
                .stress_of(&barely(kind))
                .unwrap_or_else(|| panic!("{kind:?} was measured"));
            assert_eq!(
                stress.intensity_of(kind),
                Some(Fx::ZERO),
                "{kind:?} drew something for a trace"
            );
            assert!(stress.is_clear());
        }
    }

    /// Each kind reads its own signal and nothing else. A pass that crossed two of them would
    /// still produce plausible stress, which is why this is asserted one signal at a time.
    #[test]
    fn each_kind_answers_to_one_signal() {
        let table = table();
        let full = table.normalize.todo_full_scale_per_thousand;

        let cases = [
            (
                StressKind::Cracked,
                DebtSignals {
                    markers_per_thousand: Some(Fx::from_int(full)),
                    ..DebtSignals::default()
                },
            ),
            (
                StressKind::Sparse,
                DebtSignals {
                    large_file_share: Some(Fx::ONE),
                    ..DebtSignals::default()
                },
            ),
            (
                StressKind::Restless,
                DebtSignals {
                    stability: Some(Fx::ZERO),
                    ..DebtSignals::default()
                },
            ),
        ];

        for (kind, debt) in cases {
            let stress = table.stress_of(&debt).expect("one signal was measured");
            let drawn: alloc::vec::Vec<StressKind> = stress.present().map(|(k, _)| k).collect();
            assert_eq!(drawn, [kind], "{kind:?}'s signal drew the wrong kind");
        }
    }

    /// The middle of the range, so the ceiling is a scale rather than a switch. A half-strength
    /// signal draws half as much stress as a full one.
    #[test]
    fn intensity_is_proportional_to_the_signal() {
        let table = table();
        let half = DebtSignals {
            large_file_share: Some(Fx::HALF),
            ..DebtSignals::default()
        };
        let whole = DebtSignals {
            large_file_share: Some(Fx::ONE),
            ..DebtSignals::default()
        };

        let at_half = table
            .stress_of(&half)
            .unwrap()
            .intensity_of(StressKind::Sparse)
            .unwrap();
        let at_full = table
            .stress_of(&whole)
            .unwrap()
            .intensity_of(StressKind::Sparse)
            .unwrap();

        assert_eq!(at_half.mul(Fx::from_int(2)), at_full);
        assert!(at_half > Fx::ZERO);
    }

    #[test]
    fn a_section_that_breaks_a_stated_rule_is_refused() {
        let base = table().stress;

        // Past half, stress has replaced the material it is supposed to coexist with.
        for ceiling in [0, 501, 1000] {
            let error = Rules { ceiling, ..base }
                .validate()
                .expect_err("should have been refused");
            assert_eq!(
                error.row, "ceiling",
                "{ceiling} was refused for the wrong reason"
            );
            assert_eq!(error.kind, None);
        }

        // Every kind's floor, one at a time, at both ends.
        for kind in StressKind::ALL {
            for bad in [0, 1001] {
                let mut present_at = base.present_at;
                match kind {
                    StressKind::Cracked => present_at.cracked = bad,
                    StressKind::Sparse => present_at.sparse = bad,
                    StressKind::Restless => present_at.restless = bad,
                }
                let error = Rules { present_at, ..base }
                    .validate()
                    .expect_err("should have been refused");
                assert_eq!(error.row, "present_at");
                assert_eq!(error.kind, Some(kind), "the wrong kind was named");
            }
        }
    }

    /// The message has to name the row a person would edit, or a refused table is a puzzle.
    #[test]
    fn a_refusal_names_the_row_in_the_file() {
        let error = StressError {
            row: "present_at",
            kind: Some(StressKind::Restless),
            detail: "…",
        };
        assert!(
            alloc::format!("{error}").contains("stress.present_at.restless"),
            "{error}"
        );
    }
}
